version: '3'
services:

  lambda-app:
    image: adcontor7/lambda-spark
    container_name: lambda-app
    depends_on:
      - spark-worker-1
      - spark-worker-2
      - hadoop-datanode1
      - hadoop-datanode2
      - redis
      - zookeeper
      - kafka
    environment:
      ENABLE_INIT_DAEMON: "false"


  redis:
    image: redis
    container_name: redis
    user: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - kafka:/var/lib/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1





  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    env_file:
      - ./hadoop.env
    environment:
      CLUSTER_NAME: test
    ports:
      - 50070:50070
      - 9000:9000
      - 8020:8020

  hadoop-datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-datanode1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:50070"
    env_file:
      - ./hadoop.env
   
  hadoop-datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: hadoop-datanode2
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    depends_on:
      - hadoop-namenode
      - hadoop-datanode1
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:50070"
    env_file:
      - ./hadoop.env
  



  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      INIT_DAEMON_STEP: "setup_spark"
      #- "constraint:node==<yourmasternode>"
  spark-worker-1:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      #- "constraint:node==<yourworkernode>"
  spark-worker-2:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      #- "constraint:node==<yourworkernode>"  

  

    
volumes:
  kafka:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:


