FROM adcontor7/spark-scala-template

MAINTAINER Adrián Contreras <adcontor7@gmail.com>

ENV SPARK_APPLICATION_MAIN_CLASS adcontor7.lambda.spark.Application
ENV SPARK_APPLICATION_ARGS "kafka:9092 wordcount redis:6379 hdfs://hadoop-namenode/"